### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by XavierColombel** [smartlook/smartlook-client#1]
```
componentDidMount() {
    /*Smartlook*/
    smartlookClient.init("e6069718e0xxxxxxxxxxxxxxxxxx22f05ea3b");
  }

```
I've got this error:
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/xxxx/GitHub/xxxx/www/node_modules/smartlook-client/index.js:35:4)
```

**Comment by amertak** [comment]
Hi,
do you use server side rendering?
If not, can you specify the stack you are using? (webpack, ...)

**Comment by XavierColombel** [comment]
Yes, we are using NextJS.

**Comment by amertak** [comment]
I released version 2.2.0. Try it now please.

It was not tested in server side rendering. Will do later this week.

**Comment by XavierColombel** [comment]
I've tested, there is no more error but it's not recording anything.

**Comment by XavierColombel** [comment]
With your new version it's working! I forgot to update my SmartLook ID. Thanks a lot !
