### ISSUE TITLE
Client blocked by ad blockers

### ISSUE THREAD

**Issue by dandv** [smartlook/smartlook-client#10]
Unsurprisingly, the [recorder script](https://github.com/smartlook/smartlook-client/blob/master/index.ts#L22) is blocked by ad blockers.

![image](https://user-images.githubusercontent.com/33569/83196618-15b57f00-a0f1-11ea-9816-af64859b57ac.png)

Would it be possible to actually include the code in this package (instead of it being a thin wrapper over the script), in order to avoid that problem?

**Comment by amertak** [comment]
Hi, recorder is blocked by ad blockers and we are not going to deny users their right to not be recorded. If they have ad blocker, we respect that.
