### ISSUE TITLE
Custom event properties

### ISSUE THREAD

**Issue by rhanesoghlyan** [smartlook/smartlook-client#11]
There are no possibilities for adding custom event properties for the each event. 
Please check the official documentation of the SmartLook.

https://smartlook.github.io/docs/web/custom-event-props/

**Comment by amertak** [comment]
Hi @rhanesoghlyan, 

you are right, API is missing in the client. We will fix the issue asap.

**Comment by amertak** [comment]
Released v4.5.1 fix issue fixed.
