### ISSUE TITLE
CSS not loading in recordings.

### ISSUE THREAD

**Issue by RajatKumarChahar** [smartlook/smartlook-client#15]
In Recordings recorded by Smartlook, the CSS of the web pages are not loading. 
On inspecting I found it was the CORS issue. My CSS files are not on any cloud storage, they are all present on my local machine but still its giving CORS error and CSS is not loading in my screens recordings. 

<img width="1246" alt="Screenshot 2021-05-05 at 6 29 30 PM" src="https://user-images.githubusercontent.com/50018778/117144798-fda1b180-adcf-11eb-8602-62ebca025a42.png">

**Comment by amertak** [comment]
Hi, currently we do not support CSS files that are local.

You can try allowing CORS on the local files as proxy should redirect you to your local file after failing to download it.

**Comment by RajatKumarChahar** [comment]
So, basically when i'll deploy my application, let say on EC2 then it will load CSS files?

**Comment by amertak** [comment]
Yes.

**Comment by gunner963** [comment]
so in my case it is being proxied and then comes back so I don't think CORS is an issue, but in response headers I see it as text/html 
front end is react 
any idea on how can we fix this ?
