### ISSUE TITLE
User Information not logged in smartlook dashboard via identify method in react

### ISSUE THREAD

**Issue by radovan-liska** [smartlook/smartlook-client#16]
Hi, I am trying to use smartlookClient.identify() function in my react app, but without success. SmartlookClient is initialized correctly and the recordings are working correctly. I use the following example:

```js
import smartlookClient from 'smartlook-client';

export default class DefaultLayout extends React.Component<IProps, IState> {

	identifyUser(){
		console.log("identify")
		smartlookClient.identify(123, {
			name: "radovan",
			email: "r.email@gmail.eu"
		});
	}

	componentDidMount() {
		if(!smartlookClient.initialized()){
			console.log("init" + process.env.REACT_APP_SMARTLOOK)
			smartlookClient.init(process.env.REACT_APP_SMARTLOOK)  // working, correct id
		}
	}
	componentWillUnmount(){
		if(smartlookClient.initialized()){
			console.log("smartlook uninitialized") // making sure it was not unmounted in meantime
			smartlookClient.disable()
		}
	}
	
	render() {
		this.identifyUser()
		return (<div>MyApp</div>)
	}
}

````

I tried to put this.identifyUser() into componentDidMount() as well, but did not work neither

smartlook-client version: 5.0.0
react version: 16.8.4
Environment: localhost

Could you please write me what i am doing wrong? thank you very much.

**Comment by Joozty** [comment]
Hi @radovan-liska,

thanks for using smartlook. It's definitely not a good idea to call identify in `render` method since this method is called even before [`componentDidMount`](https://reactjs.org/docs/react-component.html#componentdidmount) 

When you say you tried to put identify in componentDidMount how did you do it. Can you share the code example?

Did it look like this: 
```js
	componentDidMount() {
		if(!smartlookClient.initialized()){
			console.log("init" + process.env.REACT_APP_SMARTLOOK)
			smartlookClient.init(process.env.REACT_APP_SMARTLOOK)  // working, correct id
                        this.idetifyUser()
		}
	}
```

If so did you notice any error in the console or something that can help us to debug this issue? 🙂

**Comment by amertak** [comment]
Hi, 

I would also like to add that identify method is under GDPR (if EU IP) so consent is needed otherwise there will be a warning in the console like 
```
User has not given consent to use API
```

I recommend to look at https://smartlook.github.io/docs/web/identify-visitor and https://smartlook.github.io/docs/web/gdpr

**Comment by radovan-liska** [comment]
Hi @Joozty,
yes i put the code as you wrote again. This approach i tried before.  There is no error, no warning. Just one thing i noticed in browser console : Request to access cookie or storage on “https://events-writer.smartlook.com/rec/events?rid=ASXFedOdHHa&sid=dfwefsdfe_3&key=XXXX&vid=XXXXX&group=30d&source=website&s=1” was blocked because it came from a tracker and content blocking is enabled. But in network tab some requests are passing. Could it be a potential issue?  @amertak  thanks for proposal

**Comment by radovan-liska** [comment]
> 
> 
> Hi @Joozty,
> yes i put the code as you wrote again. This approach i tried before. There is no error, no warning. Just one thing i noticed in browser console : Request to access cookie or storage on “[https://events-writer.smartlook.com/rec/events?rid=ASXFedOdHHa&sid=dfwefsdfe_3&key=XXXX&vid=XXXXX&group=30d&source=website&s=1”](https://events-writer.smartlook.com/rec/events?rid=ASXFedOdHHa&sid=dfwefsdfe_3&key=XXXX&vid=XXXXX&group=30d&source=website&s=1%E2%80%9D) was blocked because it came from a tracker and content blocking is enabled. But in network tab some requests are passing. Could it be a potential issue? @amertak thanks for proposal. I followed the first one

I turned content tracking off , there is really no warning , no issue, but the user information are not there. Is it possible to turn some additional debug info on ?

**Comment by radovan-liska** [comment]
Hi @Joozty , @amertak , after following: https://help.smartlook.com/en/articles/3422023-gdpr-and-smartlook-options , where i added consent everything started to be recorded as expected. Perhaps i had to mention I am from Europe/Czech and then the GDPR is applied to my application. Just a suggestion if you like: To mention in https://smartlook.github.io/docs/web/identify-visitor article that for Europe it is required to add consent from user if you want to user information to be logged in dashboard. Thank you very much for your support. I appreciate it.

**Comment by Joozty** [comment]
Glad to hear that. In that case, I am going to close this issue. If you have any further questions don't hesitate to fill a new issue or reopen this one. 🙂
