### ISSUE TITLE
Not able to identify the customer in my React js Java script web application

### ISSUE THREAD

**Issue by dusianandakumar** [smartlook/smartlook-client#17]
I am adding the unique customer id for identifying the customer, but in the Smartlook dashboard I am not able to track those details.Please check it.

below code the way I am calling the Smartlook client for tracking after initialisation.

smartlookClient.identify(response.getCustomerId(), {
            name: response.getCustomerName(),
            email: response.getPersonalEmail(),
        });

**Comment by doankhoi** [comment]
@dusianandakumar I think you forgot enable `Identify users via API` on project settings. It's a in paid packages
<img width="675" alt="Screen Shot 2021-06-19 at 3 36 44 PM" src="https://user-images.githubusercontent.com/7965224/122636618-693ba600-d114-11eb-8841-ccff9f301073.png">

**Comment by pinheiroandre** [comment]
I'm also having the same problem, and all recording settings are active, but it still doesn't save user data.

Code after initialize smartlookClient:
```typescript
smartlookClient.identify(user.id, {
    name: user.name,
    email: user.email
})
```

Smartlook settings: 
![image](https://user-images.githubusercontent.com/29846210/128503815-2850fa5f-7f7f-4eb1-82ca-9c086c88ac95.png)

User Record:
![image](https://user-images.githubusercontent.com/29846210/128503887-1ab68164-ac7c-46fd-9333-9dd138c340c3.png)

**Comment by amertak** [comment]
Hi @pinheiroandre,

visitors from Brazil are under https://lgpd-brazil.info/ and we need your signed DPA and also consent from visitors to be able to identify them.

**Comment by Pajk** [comment]
You can find more info in our docs https://docs.smartlook.com/docs/web/gdpr. It says GDPR but applies also for Brazil (LGPD) and California (CCPA).
