### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Skope10** [smartlook/smartlook-client#21]
The following error occurs after interacting with an input when I initialized Smartlook

This is how I initialize Smartlook:
```
import sl from 'smartlook-client';

const useSmartlook = (): void => {
  useEffect(() => {
    if (!sl.initialized()) {
      initialize();
    }
  }, []);
};
```

![image](https://user-images.githubusercontent.com/34196060/176480779-807dd511-a3a6-44ae-b9fc-6cf9dea75332.png)

**Comment by Joozty** [comment]
@Skope10 thanks for your report. Is your website publicly available so I could take I look or even better could you please provide us with a minimal reproducible example by any chance?

**Comment by bscaspar** [comment]
@Joozty here is a CSB link: https://codesandbox.io/s/mutable-rgb-xoorph?file=/src/App.tsx

To reproduce, select the input on the screen then wait ~5 seconds. 

Changing the hidden `input` field `id` prop to anything but `id` prevents the error from happening. As does removing the `useSmartlook` hook.

**Comment by Joozty** [comment]
@bscaspar Thanks a lot. It is really appreciated. I identified the problem and prepared a fix which will get released tomorrow at some point. 

To describe the issue we record IDs of elements so they can be used in events filtering and many other places of our app. When you have a structure like this and you try to access the form's id via `document.querySelector('#test').id` the result is not a string as one would expected but the input element itself.  We were aware of this behaviour but unfortunately did not cover it at all places. Obviously the most straigthforward solution is using [`getAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) method.

```
<form id="test">
    <input id="id">
</form>
```

Thanks again for your report and MRE. I will update you once it is released.

**Comment by bscaspar** [comment]
Sounds good thank you for the quick response!

**Comment by bscaspar** [comment]
@Joozty should we look for a patch version of the package?

**Comment by Joozty** [comment]
No need it should work without doing any changes in your codebase. This package is just a wrapper around our web-sdk script which is downloaded once you call initialize method.
