### ISSUE TITLE
Keeping the path from the visitor

### ISSUE THREAD

**Issue by mauriciord** [smartlook/smartlook-client#22]
I've got a React application and when the user accesses the pages that don't require authentication like `signin` and `signup`, should I use a `anonymize()` and after I get the user from their authentication, should I call `identify()`  with that userId and others properties from that userId?

Doing this, will the recordings keep the videos before the login and after the login in the same session?

**Comment by mauriciord** [comment]
sorry about opening this issue here, but I haven't found anything related to this doubt about keeping the session.

**Comment by Joozty** [comment]
Hi @mauriciord 👋. Calling `anonymize` will start a new recording. If you call it before identify it will basically start a new video. To answer your question I would recommend calling anonymize only when the user logs out

**Comment by Joozty** [comment]
I am closing this one for inactivity. Feel free to reopen if you have any follow-up questions.
