### ISSUE TITLE
Use this smartlook-client package as types in my TypeScript project for Google Tag Manager injected smartlook

### ISSUE THREAD

**Issue by josh08h** [smartlook/smartlook-client#26]
I have injected `smartlook` into my website using the official Smartlook Google Tag & am creating a helper class in my TypeScript project that uses `window.smartlook`, for example:

```typescript
import smartlookClient from "smartlook-client";

declare global {
  interface Window {
    smartlook: typeof smartlookClient
  }
}

class SmartlookSupport {
  identifySession() {
    // custom code...
    window.smartlook("identify", "123")
  }
}
```

I would like to use the types from the `smartlook-client` package in the `SmartlookSupport` class but need to ensure that the GTM injected `smartlook` has the same interface as `smartlookClient`.

Is there a way I can pin the version of the `smartlook` client injected by GTM so that it matches the types of a pinned `smartlook-client`?

**Comment by Joozty** [comment]
Hi @josh08h 👋,

I would not recommend using types from `smartlook-client`  as the code here is slightly different from the code loaded via GTM.  I can provide you with the types we use. Obviously, if something changes you need to adjust it but I can ensure we do not change the current API at all only adding new features. If something changes we always notify our customers via email ahead so you will have time to adjust your code properly. I will think about publishing these types somewhere so you do not need to maintain them in your codebase but I cannot promise you any ETA. In the meantime please copy it to your codebase. Is that ok with you?



```ts
 interface ApiFunctions {
	anonymize: []
	disable: [disable: boolean]
	error: [customError: string | Record<string, unknown> | Error]
	identify: [visitorUId: string, visitorProps?: Record<string, unknown>]
	init: [projectKey: string, options?: Record<string, unknown>]
	navigation: [url: string]
	pause: []
	properties: [properties: Record<string, unknown>]
	record: [
		params: {
			emails?: boolean
			forms?: boolean
			ips?: true
			numbers?: boolean
		},
	]
	resume: []
	stop: []
	track: [eventName: string, eventProperties?: Record<string, unknown>]
}

interface Smartlook {
	key?: string
	playUrl?: string
	recordId?: string
	sessionId?: string
	visitorId?: string
	(callback: () => void): void
	<K extends keyof ApiFunctions>(methodName: K, ...args: ApiFunctions[K]): Promise<void>
}
```

**Comment by josh08h** [comment]
That's perfect - thanks a lot @Joozty  👍

**Comment by josh08h** [comment]
@Joozty Would I be able to hijack this issue and ask an unrelated question?

We are using GTM to inject `smartlook` into the `window` and need a way to determine when the object has been added to the `window`. Does `smartlook` issue an event at all to notify that it has been added to the `window` sucessfully? Without this we may be invoking `smartlook` _before_ it has been added to the `window` by GTM & the `recorder.js` script.

Thanks

**Comment by Joozty** [comment]
Sadly smartlook does not issue any event. Maybe GTM has some way to determine it but I doubt that. (I am not very familiar with it). I believe the only way right now is to write your own wrapper with an interval checker. Something like this:

```ts
class SmartlookWrapper {
	private isSmartlookLoaded = false
	private waitingApiCalls = []
	constructor() {
		const initiationInterval = setInterval(() => {
			if (window.smartlook) {
				this.isSmartlookLoaded = true
				this.waitingApiCalls.forEach((...args) => {
					window.smartlook(...args)
				})
				this.waitingApiCalls = []
				clearInterval(initiationInterval)
			}
		}, 100)
	}

	identifySession() {
		if (!this.isSmartlookLoaded) {
			this.waitingApiCalls.push(['identify', '123'])
		} else {
			window.smartlook('identify', '123')
		}
	}
}
```

I know it is not ideal but that is the only option right now.

PS: If you insert our code directly then smartlook object is instantiated straight away. No need for this wrapper.
