### ISSUE TITLE
SmartLook with Angular 8

### ISSUE THREAD

**Issue by enigcreator** [smartlook/smartlook-client#32]
Hi!
I am using the [npm package](https://www.npmjs.com/package/smartlook-client) to implement SmartLook in my Ionic Angular 8 project.
But receiving the error on console after initialise the smartLook with line below:

`smartlookClient.init('PROJECT_KEY', {region: 'eu'})`

**ERROR: SmartLook not recording. Reason: Mobile project cannot accept website traffic.**

need help. thanks!

**Comment by Joozty** [comment]
Hi @enigcreator 👋 

You are trying to record to mobile project which is not supported by our SDK as the error says. If you want to use our SDK for web. i.e. this package, you need to use web or [combined project](https://help.smartlook.com/en/articles/6088359-combined-website-and-mobile-project). 

If you have any further questions I recommend you contacting our awesome [support](https://www.smartlook.com/contact/) they can help you setup your project or explain which project is the best for you.
