### ISSUE TITLE
not able to add array values to global properties

### ISSUE THREAD

**Issue by mborisov-grubhub** [smartlook/smartlook-client#38]
As far as I can see after some testing, it's not possible to use arrays in call to 'properties'.
For example: `Smartlook.properties({testArray: [1,2,3]})`

So do I just miss something or is it really possible to use only `string | number | boolean` as properties values?

I'm using [smartlook-client package](https://www.npmjs.com/package/smartlook-client) (v 8.2.0) in react based project.

**Comment by amertak** [comment]
Hi @mborisov-grubhub

You are right as only primitive values can be used for identify and properties API calls.

```typescript
Record<string, string | number | boolean>
```
