### ISSUE TITLE
Console log recording freezes whole browser tab

### ISSUE THREAD

**Issue by jakubzitny** [smartlook/smartlook-client#4]
Hi,

we've recently added `smartlook` to our website and noticed that when we turn on the console log recording in smartool settings, smartlook freezes the whole app.

The point when this is happening is when we're initializing a pretty complicated canvas and we are printing a lot of debug/log messages in console. Not sure if the canvas or the console is the root casue, probably the console because disabling it in smartlook fixes it.

When we remove `smartlook-client` everything works properly.

Is there something we can do with this?

**Comment by amertak** [comment]
Hi,
thanks for reporting the issue.

We will look into, it's possible that there is some performance bottleneck.

To help us with fixing it, can you tell us how much of the console logs do you log and how big are the data approximately?
Is it happening in all browsers?
Is it possible for you to show sandbox with similar code that is causing the issue or url where the issue happens?

Thanks

**Comment by jakubzitny** [comment]
I've tried it in our dev mode and in production mode (where not all logs are printed to console, but they exist and you guys probably touch them somehow, similarly `sentry` catches them as well). After the action where this problem happened, there was **~120kB** of logs in just few seconds.

We'll talk in the team about sharing a sandbox version where this is reproducible, but we'd have to figure out a way and it may take some time.

**Comment by amertak** [comment]
We have done some performance improvements on the client so this issue should be fixed for now. If it happens again. Let us know please. Thank you
