### ISSUE TITLE
Smartlook.pause + Smartlook.resume not working

### ISSUE THREAD

**Issue by QoLTech** [smartlook/smartlook-client#41]
I'm using this library in a Flutter Web project.

I'm trying to pause the recording on our web app to hide sensitive data at certain points. When the sensitive data is displayed, I call Smartlook.pause() and then when it's gone, I call Smartlook.resume(). I've checked our recordings once they're processed and it seems like the recording is either ending once I call pause(), or the call to resume() isn't working.

I've also tried disable(true/false) and that doesn't seem to work either. What could I be doing wrong? Is there another way to handle data sensitivity? I don't have access to individual HTML elements.

**Comment by Joozty** [comment]
Hi @QoLTech, thank you for your report.

I do not see anything wrong with your implementation. I suggest writing to our support with more details - your project key, and perhaps provide a testing environment if possible.

https://www.smartlook.com/contact/

**Comment by Joozty** [comment]
I am closing this issue. As previously mentioned, let's work through our excellent support team since we need more information. Thank you for your understanding.
