### ISSUE TITLE
Uncomplete polyfill of Safari requestIdleCallback and cancelIdleCallback 

### ISSUE THREAD

**Issue by montella1507** [smartlook/smartlook-client#42]
Please, check this issue

https://github.com/angular/angular/issues/53721

Not sure if the correct solution will be to complete the polyfill in your SDK or just to improve guard in angular/core. But this is little trap for angular developers :-)

**Comment by Joozty** [comment]
Thanks for your report, @montella1507. 

This is a bummer, and I would lean more towards fixing it on the Angular side. We polyfill only the APIs we need, and cancelIdleCallback would just add unnecessary code to our bundle. Maybe let's wait to see how the discussion turns out in the mentioned bug, and then we can decide.

**Comment by Joozty** [comment]
When I think about it more, it probably makes sense to add a polyfill for `cancelIdleCallback` too. Our polyfill implementation might be different from Angular's, and if we loaded our `requestIdleCallback` polyfill and `cancelIdleCallback` polyfill from Angular, it would most likely not work, as the internal implementation is different.

**Comment by montella1507** [comment]
Hi @Joozty  how does it look, please? We are going live to production in several days. So i would like to ask if it is about to be patched soon, or we should polyfill cancelIdleCallback on our own (or disable smatlook for a while). 

Thanks!

**Comment by Joozty** [comment]
@montella1507, sorry for not providing an update. The fix is prepared and will be released first thing on Monday. Is that ok with you?

**Comment by montella1507** [comment]
Definitely! Thanks a lot!

**Comment by Joozty** [comment]
Fix is released. Please try it now.
