### ISSUE TITLE
App crash (Android)

### ISSUE THREAD

**Issue by lkshh-g** [smartlook/smartlook-client#46]
I am using the flutter_smartlook: ^4.1.17 library. The app is crashing on android build (emulator, have not tested the same on real device). 

Flutter Doctor logs :
[✓] Flutter (Channel stable, 3.13.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-IN)
    • Flutter version 3.13.0 on channel stable at /Users/ofb_lokesh/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 months ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ofb_lokesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ofb_lokesh/Library/Android/sdk
    • Java binary at: /Applications/Android [Studio.app/Contents/jre/Contents/Home/bin/java](http://studio.app/Contents/jre/Contents/Home/bin/java)
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/[Xcode.app/Contents/Developer](http://xcode.app/Contents/Developer)
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google [Chrome.app/Contents/MacOS/Google](http://chrome.app/Contents/MacOS/Google) Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android [Studio.app/Contents](http://studio.app/Contents)
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio [Code.app/Contents](http://code.app/Contents)
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Lokesh’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Attaching the crash report file.**
[Smartlook-crash-report.txt](https://github.com/smartlook/smartlook-client/files/14329954/Smartlook-crash-report.txt)

**Comment by Joozty** [comment]
Hi @lkshh-g , 

this package is covers only web client and does not support mobile devices. Could you please contact our support team and raise an issue? They will direct it to the appropriate team.

https://www.smartlook.com/contact/

Thank you for your understanding.
