### ISSUE TITLE
Support for Popover API in the session playback

### ISSUE THREAD

**Issue by perttumyry** [smartlook/smartlook-client#49]
We are using Popover API to make our dropdown menus appear in the top layer. This is super handy as the top layer never goes below any other element in the UI so we don't have to worry about flimsy z-index tricks or stacking context.
https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

They are supported in all modern browsers so that's why we feel confident in using this technology in our production environment.
https://caniuse.com/mdn-api_htmlelement_popover

When we playback recordings though the dropdown menus are not shown at all. Do you think you could support Popover API in the session playbacks?

We've also noticed that modals which utilize `<dialog>` element always utilize the full window height in the playbacks, but when testing with any browser they always take just the height they actually use. This is not as big of a deal breaker though as not seeing the dropdown menus in session playback at all.

**Comment by amertak** [comment]
Hello @perttumyry,

Popover API implementation is in the progress. We will be releasing it later this week or next week.

Let us know if there is anything else you are missing.

Thank you

**Comment by perttumyry** [comment]
> Popover API implementation is in the progress. We will be releasing it later this week or next week.

Awesome, looking forward to it!

> Can you please contact our support regarding the dialog issue, we should now have full support. So we can look into it more?

Will do, we'll contact support@smartlook.com and describe our `<dialog>` height issue in more detail.

**Comment by perttumyry** [comment]
Awesome, thanks for adding support for Popover API!
