### ISSUE TITLE
Confusing call convention

### ISSUE THREAD

**Issue by dandv** [smartlook/smartlook-client#7]
In the README here, the calling convention is `smartlookClient[method](...args)`, for example `smartlookClient.identify(12345, { ... })`.

At the bottom, the README links to the docs site.

There, the calling convention is `smartlookClient('method', ...args)`. For [example](https://smartlook.github.io/docs/web/identify-visitor/), `smartlook('identify', user_id);`.

**Comment by amertak** [comment]
Hi, 
this library is just a wrapper over the smartlook script.
It adds wrapper methods on everything you can call using the `smartlook('method', ...)` with added typescript typings.

Link to docs is there so you can learn more about the methods.
