### ISSUE TITLE
FR: add basic support for logging from Node

### ISSUE THREAD

**Issue by dandv** [smartlook/smartlook-client#8]
Just being able to [log custom errors](https://smartlook.github.io/docs/web/error-logging/) from server-side code, would mostly eliminate the need for using a separate error tracking service for the backend.

No need for recording, obviously. Just `.error` and `.identify`.

**Comment by Pajk** [comment]
Hello @dandv, we've already discussed this option and even came with an experimental Node.js SDK - https://github.com/smartlook/smartlook-nodejs-sdk. 

We haven't tested it for a while and it seems it's currently not working. I'll try to review it in following weeks and I'll add an option to send error events too.

There's one catch though - you'll have to propagate current session and visitor ids to your backend - https://smartlook.github.io/docs/web/recording-api/. Is that something you'll be able to do?

**Comment by dandv** [comment]
Thanks, that's good news! Not a problem to propagate the visitor id, it's in the JWT already. Can propagate the session id too.

**Comment by dandv** [comment]
@amertak: will this not be implemented after all, or is there another ticket to monitor?

**Comment by amertak** [comment]
Sorry, closed because I thought it was solved.

Asked our product manager and it should be ready at the end of Q4 2020/beginning of Q1 2021. Will let you know.

**Comment by amertak** [comment]
This feature was postponed and not in the near roadmap. Closing this.
