### ISSUE TITLE
"API is not enabled in project settings" warning in the console

### ISSUE THREAD

**Issue by dandv** [smartlook/smartlook-client#9]
I see this after initializing the client. Recording works (minus the layout being wonky).

What does the warning mean? I [can't find anything in the help](https://help.smartlook.com/en/?q=API+is+not+enabled+in+project+settings).

**Comment by amertak** [comment]
Hi @dandv 

You need to have enabled API in project settings.

![image](https://user-images.githubusercontent.com/2790687/83136540-2b1daf80-a0d7-11ea-987d-8bf9a24f1ee2.png)

**Comment by dandv** [comment]
That was enabled by default already for non-EU. My user is from the US.

**Comment by amertak** [comment]
Is't the visitor from CA US? We have still task in backlog to better communicate that we are handling CCPA same as the GDPR.

**Comment by dandv** [comment]
Yes, the visitor was from California. Do I need to check the EU switch? Or should there be a 3rd switch for California?

![image](https://user-images.githubusercontent.com/33569/83196371-a475cc00-a0f0-11ea-8db1-669569b91a82.png)

**Comment by dandv** [comment]
I can't check the EU API box during the free trial. So if that's blocking California visitors, I can't really evaluate the product.

**Comment by CiosD** [comment]
Hi @dandv, could you please contact our support through the chat on Smartlook so we can help you to solve the issue? Also, feel free to write me on dominika@smartlook.com. I will be just happy to help you. 
Thank you in advance.
